### ISSUE TITLE
When I use `deepspeed --num_gpus=8 fine_tune.py --config_path ../configs/fine-tune/echr-gpt2-small-scrubbed.yml`, one error occurs.

### ISSUE THREAD

**Issue by Ethan-Chen-plus** [microsoft/analysing_pii_leakage#6]
![image](https://github.com/microsoft/analysing_pii_leakage/assets/84905965/bafe071c-65e2-406e-95d6-f75f258afbde)
```
06/26/2023 19:45:29:WARNING:Found cached dataset ecthr_cases (/root/.cache/huggingface/datasets/ecthr_cases/alleged-violation-prediction/1.1.0/abb43f3bc3eda893f6aee5adb99d113c1b5e80e26e5ea2bd35d3b19ba0106b9a)
100%|████████████████████████████████████████████| 3/3 [00:00<00:00, 758.14it/s]
Generating train split: 0 examples [00:00, ? examples/s]
--------------------------------------------------------------------------------
Length of data: 262580. Scrubbing from 0 to 118161 (Total=118161).
--------------------------------------------------------------------------------

Traceback (most recent call last):                      
  File "/root/analysing_pii_leakage_ms/examples/fine_tune.py", line 89, in <module>
    fine_tune(*parse_args())
  File "/root/analysing_pii_leakage_ms/examples/fine_tune.py", line 58, in fine_tune
    train_dataset: RealDataset = DatasetFactory.from_dataset_args(dataset_args.set_split("train"),
  File "/root/analysing_pii_leakage/src/pii_leakage/dataset/dataset_factory.py", line 14, in from_dataset_args
    return RealDataset(dataset_args, ner_args=ner_args, env_args=env_args)
  File "/root/analysing_pii_leakage/src/pii_leakage/dataset/real_dataset.py", line 24, in __init__
    super().__init__(ner_args, env_args)
  File "/root/analysing_pii_leakage/src/pii_leakage/dataset/dataset.py", line 19, in __init__
    self._base_dataset = self._load_base_dataset()   # The dataset that this class wraps around (e.g., huggingface)
  File "/root/analysing_pii_leakage/src/pii_leakage/dataset/real_dataset.py", line 29, in _load_base_dataset
    return load_dataset(self.dataset_args.dataset_path, cache_dir=self.dataset_args.cache_dir,
  File "/opt/micromamba/envs/py310/lib/python3.10/site-packages/datasets/load.py", line 1742, in load_dataset
    builder_instance.download_and_prepare(
  File "/opt/micromamba/envs/py310/lib/python3.10/site-packages/datasets/builder.py", line 814, in download_and_prepare
    self._download_and_prepare(
  File "/opt/micromamba/envs/py310/lib/python3.10/site-packages/datasets/builder.py", line 1423, in _download_and_prepare
    super()._download_and_prepare(
  File "/opt/micromamba/envs/py310/lib/python3.10/site-packages/datasets/builder.py", line 905, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/opt/micromamba/envs/py310/lib/python3.10/site-packages/datasets/builder.py", line 1374, in _prepare_split
    for key, record in logging.tqdm(
  File "/opt/micromamba/envs/py310/lib/python3.10/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/root/.cache/huggingface/modules/datasets_modules/datasets/echr/d80e60dcf543a073f919056683dc89eecbb949af55da051ff7a3120aeec3b7ee/echr.py", line 102, in _generate_examples
    result: Tuple[str, ListPII] = self._tagger.pseudonymize(text)
  File "/root/analysing_pii_leakage/src/pii_leakage/ner/flair_tagger.py", line 77, in pseudonymize
    text[pii.start:pii.end] = self.ner_args.anon_token
TypeError: 'str' object does not support item assignment
[2023-06-26 19:45:32,657] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 157564
[2023-06-26 19:45:32,886] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 157565
[2023-06-26 19:45:33,115] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 157566
[2023-06-26 19:45:33,384] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 157567
[2023-06-26 19:45:33,614] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 157568
[2023-06-26 19:45:33,843] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 157569
[2023-06-26 19:45:33,844] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 157570
[2023-06-26 19:45:34,192] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 157571
[2023-06-26 19:45:34,541] [ERROR] [launch.py:434:sigkill_handler] ['/opt/micromamba/envs/py310/bin/python3.10', '-u', 'fine_tune.py', '--local_rank=7', '--config_path', '../configs/fine-tune/echr-gpt2-small-scrubbed.yml'] exits with return code = 1
```

**Comment by vatsal-kr** [comment]
I replaced line 77 (`text[pii.start:pii.end] = self.ner_args.anon_token`) with `text = text[:pii.start] + self.ner_args.anon_token + text[pii.end:]`. Worked for me
