### ISSUE TITLE
"CUDA out of memory" error in generate().

### ISSUE THREAD

**Issue by Nozima29** [microsoft/analysing_pii_leakage#9]
I was successfully able to fine-tune however evaluate is being problematic.
Currently I have 2 GPUs on my machine and generate() method in  evaluate.py is throwing memory error, as it's using only one GPU and having following Error:

```
> Instantiating the naive extraction attack.
Generating with LM:   0%|                                                                                 | 0/4 [00:16<?, ?it/s]
Traceback (most recent call last):
  File "/home/nozima/projects/analysing_pii_leakage/examples/evaluate.py", line 161, in <module>
    evaluate(*parse_args())
  File "/home/nozima/projects/analysing_pii_leakage/examples/evaluate.py", line 80, in evaluate
    generated_pii: dict = attack.attack(lm)  # PII -> count
  File "/home/nozima/projects/analysing_pii_leakage/src/pii_leakage/attacks/extraction/naive_extraction.py", line 36, in attack
    generated_text: GeneratedTextList = lm.generate(sampling_args)
  File "/home/nozima/anaconda3/envs/pii-leakage/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/nozima/projects/analysing_pii_leakage/src/pii_leakage/models/language_model.py", line 206, in generate
    generated_data.extend(generate_batch(input_ids, attention_mask))
  File "/home/nozima/projects/analysing_pii_leakage/src/pii_leakage/models/language_model.py", line 188, in generate_batch
    soft_scores = [torch.softmax(
  File "/home/nozima/projects/analysing_pii_leakage/src/pii_leakage/models/language_model.py", line 188, in <listcomp>
    soft_scores = [torch.softmax(
RuntimeError: CUDA out of memory. Tried to allocate 198.00 MiB (GPU 0; 47.54 GiB total capacity; 36.04 GiB already allocated; 165.62 MiB free; 46.27 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by LuckMonkeys** [comment]
Hi, @Nozima29 , have you found a solution to this issue yet? could you please share more details? 
Thanks!
